spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bingchuanfeiyu/cscp.git
          username: 2861124797@qq.com
          password: kz13986088105
  profiles:
    active: dev
server:
  port: 8200
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
eureka:
  client:
    service-url:
      defaultZone: http://47.93.232.115:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 47.93.232.115
spring:
  profiles: dev
---
eureka:
  client:
    service-url:
      defaultZone: http://47.93.40.90:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 47.93.40.90
spring:
  profiles: prod