eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
spring:
  rabbitmq:
    host: 47.94.147.215
    port: 5672
    username: guest
    password: guest
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bingchuanfeiyu/cscp.git
          username: 2861124797@qq.com
          password: kz13986088105
server:
  port: 8200
management:
  endpoints:
    web:
      exposure:
        include: "*"
