spring:
  application:
    name: euraka
server:
  port: 8761
eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8762/eureka/
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
